In [2]:
import pandas as pd

In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Rythem\Downloads\archive (1) (1)\Medicine_Details.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Shape: (11825, 9)

Columns:
['Medicine Name', 'Composition', 'Uses', 'Side_effects', 'Image URL', 'Manufacturer', 'Excellent Review %', 'Average Review %', 'Poor Review %']

First 5 rows:

,Medicine Name,Composition,Uses,Side_effects,Image URL,Manufacturer,Excellent Review %,Average Review %,Poor Review %
0,Avastin 400mg Injection,Bevacizumab (400mg),Cancer of colon and rectum Non-small cell lun...,Rectal bleeding Taste change Headache Noseblee...,"https://onemg.gumlet.io/l_watermark_346,w_480,...",Roche Products India Pvt Ltd,22,56,22
1,Augmentin 625 Duo Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,Vomiting Nausea Diarrhea Mucocutaneous candidi...,"https://onemg.gumlet.io/l_watermark_346,w_480,...",Glaxo SmithKline Pharmaceuticals Ltd,47,35,18
2,Azithral 500 Tablet,Azithromycin (500mg),Treatment of Bacterial infections,Nausea Abdominal pain Diarrhea,"https://onemg.gumlet.io/l_watermark_346,w_480,...",Alembic Pharmaceuticals Ltd,39,40,21
3,Ascoril LS Syrup,Ambroxol (30mg/5ml) + Levosalbutamol (1mg/5ml)...,Treatment of Cough with mucus,Nausea Vomiting Diarrhea Upset stomach Stomach...,"https://onemg.gumlet.io/l_watermark_346,w_480,...",Glenmark Pharmaceuticals Ltd,24,41,35
4,Aciloc 150 Tablet,Ranitidine (150mg),Treatment of Gastroesophageal reflux disease (...,Headache Diarrhea Gastrointestinal disturbance,"https://onemg.gumlet.io/l_watermark_346,w_480,...",Cadila Pharmaceuticals Ltd,34,37,29

In [4]:
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nData types:")
print(df.dtypes)

Shape: (11825, 9)

Missing values:
Medicine Name         0
Composition           0
Uses                  0
Side_effects          0
Image URL             0
Manufacturer          0
Excellent Review %    0
Average Review %      0
Poor Review %         0
dtype: int64

Data types:
Medicine Name           str
Composition             str
Uses                    str
Side_effects            str
Image URL               str
Manufacturer            str
Excellent Review %    int64
Average Review %      int64
Poor Review %         int64
dtype: object

In [5]:
print(df.columns.tolist())
display(df.head())

['Medicine Name', 'Composition', 'Uses', 'Side_effects', 'Image URL', 'Manufacturer', 'Excellent Review %', 'Average Review %', 'Poor Review %']

,Medicine Name,Composition,Uses,Side_effects,Image URL,Manufacturer,Excellent Review %,Average Review %,Poor Review %
0,Avastin 400mg Injection,Bevacizumab (400mg),Cancer of colon and rectum Non-small cell lun...,Rectal bleeding Taste change Headache Noseblee...,"https://onemg.gumlet.io/l_watermark_346,w_480,...",Roche Products India Pvt Ltd,22,56,22
1,Augmentin 625 Duo Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,Vomiting Nausea Diarrhea Mucocutaneous candidi...,"https://onemg.gumlet.io/l_watermark_346,w_480,...",Glaxo SmithKline Pharmaceuticals Ltd,47,35,18
2,Azithral 500 Tablet,Azithromycin (500mg),Treatment of Bacterial infections,Nausea Abdominal pain Diarrhea,"https://onemg.gumlet.io/l_watermark_346,w_480,...",Alembic Pharmaceuticals Ltd,39,40,21
3,Ascoril LS Syrup,Ambroxol (30mg/5ml) + Levosalbutamol (1mg/5ml)...,Treatment of Cough with mucus,Nausea Vomiting Diarrhea Upset stomach Stomach...,"https://onemg.gumlet.io/l_watermark_346,w_480,...",Glenmark Pharmaceuticals Ltd,24,41,35
4,Aciloc 150 Tablet,Ranitidine (150mg),Treatment of Gastroesophageal reflux disease (...,Headache Diarrhea Gastrointestinal disturbance,"https://onemg.gumlet.io/l_watermark_346,w_480,...",Cadila Pharmaceuticals Ltd,34,37,29

In [7]:
# Remove duplicate medicine names
df = df.drop_duplicates(subset="Medicine Name", keep="first").reset_index(drop=True)

print("New Shape:", df.shape)
print("Duplicate Medicine Names:", df["Medicine Name"].duplicated().sum())

New Shape: (11498, 9)
Duplicate Medicine Names: 0

In [8]:
print(df["Medicine Name"].sample(20).tolist())

['Oframax Forte 1.5g Injection', 'Macpod 200 Tablet', 'Aerotrop-F Inhaler', 'Pansped 40 Tablet', 'Valrate CR 500 Tablet', 'Priglip M 500mg/20mg Tablet', 'AD 100mg Capsule', 'Aciloc-S Suspension Sugar Free', 'Tripride 1 LV Tablet SR', 'L Montus Oral Suspension', 'Telkonol  20 Tablet', 'Espin-AT Tablet', 'Asert D Tablet ER', 'Rantac 150 Tablet', 'Biodens Hair Lotion', 'Recool Eye Drop', 'Telekast-L Kid Syrup', 'Zifi Drop', 'Histo Calamine Lotion', 'Isryl-M 4 Forte Tablet PR']

In [9]:
display(df[["Medicine Name", "Composition", "Uses", "Side_effects"]].head(10))

,Medicine Name,Composition,Uses,Side_effects
0,Avastin 400mg Injection,Bevacizumab (400mg),Cancer of colon and rectum Non-small cell lun...,Rectal bleeding Taste change Headache Noseblee...
1,Augmentin 625 Duo Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,Vomiting Nausea Diarrhea Mucocutaneous candidi...
2,Azithral 500 Tablet,Azithromycin (500mg),Treatment of Bacterial infections,Nausea Abdominal pain Diarrhea
3,Ascoril LS Syrup,Ambroxol (30mg/5ml) + Levosalbutamol (1mg/5ml)...,Treatment of Cough with mucus,Nausea Vomiting Diarrhea Upset stomach Stomach...
4,Aciloc 150 Tablet,Ranitidine (150mg),Treatment of Gastroesophageal reflux disease (...,Headache Diarrhea Gastrointestinal disturbance
5,Allegra 120mg Tablet,Fexofenadine (120mg),Treatment of Sneezing and runny nose due to al...,Headache Drowsiness Dizziness Nausea
6,Avil 25 Tablet,Pheniramine (25mg),Treatment of Allergic conditionsTreatment of R...,Sedation
7,Aricep 5 Tablet,Donepezil (5mg),Alzheimer's disease,Common cold Urinary incontinence Rash Nausea D...
8,Amoxyclav 625 Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,Vomiting Nausea Diarrhea Mucocutaneous candidi...
9,Atarax 25mg Tablet,Hydroxyzine (25mg),Treatment of AnxietyTreatment of Skin conditio...,Sedation Nausea Vomiting Upset stomach Constip...

In [10]:
# Create text column for Transformer
df["medicine_text"] = df["Medicine Name"].astype(str).str.strip()

print(df[["Medicine Name", "medicine_text"]].head())

              Medicine Name             medicine_text
0   Avastin 400mg Injection   Avastin 400mg Injection
1  Augmentin 625 Duo Tablet  Augmentin 625 Duo Tablet
2       Azithral 500 Tablet       Azithral 500 Tablet
3          Ascoril LS Syrup          Ascoril LS Syrup
4         Aciloc 150 Tablet         Aciloc 150 Tablet

In [11]:
print("Total medicines:", len(df))
print("Total text values:", df["medicine_text"].notna().sum())

Total medicines: 11498
Total text values: 11498

In [13]:
%pip install -U sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-5.7.0-py3-none-any.whl.metadata (18 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.15.0-py3-none-any.whl.metadata (32 kB)
Collecting tokenizers>=0.19 (from sentence-transformers)
  Downloading tokenizers-0.23.1-cp310-abi3-win_amd64.whl.metadata (10 kB)
Collecting huggingface-hub>=0.23.0 (from sentence-transformers)
  Downloading huggingface_hub-1.27.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: torch>=1.11.0 in .\.deepvenv311\Lib\site-packages (from sentence-transformers) (2.13.0)
Requirement already satisfied: numpy>=1.20.0 in .\.deepvenv311\Lib\site-packages (from sentence-transformers) (2.4.6)
Requirement already satisfied: scikit-learn>=0.22.0 in .\.deepvenv311\Lib\site-packages (from sentence-transformers) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in .\.deepvenv311\Lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in .\.deepvenv311\Lib\site-packages (from sentence-transformers) (4.16.0)
Collecting tqdm>=4.0.0 (from sentence-transformers)
  Downloading tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: packaging>=20.0 in .\.deepvenv311\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in .\.deepvenv311\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Collecting regex>=2025.10.22 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading regex-2026.7.19-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting tokenizers>=0.19 (from sentence-transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting typer (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading typer-0.27.1-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.8.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub>=0.23.0->sentence-transformers)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in .\.deepvenv311\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.32.2)
Requirement already satisfied: fsspec>=2023.5.0 in .\.deepvenv311\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.7.0)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface-hub>=0.23.0->sentence-transformers)
  Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in .\.deepvenv311\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: colorama in .\.deepvenv311\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub>=0.23.0->sentence-transformers) (0.4.6)
Requirement already satisfied: anyio in .\.deepvenv311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in .\.deepvenv311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in .\.deepvenv311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in .\.deepvenv311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in .\.deepvenv311\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: joblib>=1.4.0 in .\.deepvenv311\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\.deepvenv311\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\.deepvenv311\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools>=77.0.3 in .\.deepvenv311\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in .\.deepvenv311\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in .\.deepvenv311\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in .\.deepvenv311\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\.deepvenv311\Lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in .\.deepvenv311\Lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Collecting shellingham>=1.3.0 (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=13.8.0 in .\.deepvenv311\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (15.0.0)
Collecting annotated-doc>=0.0.2 (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\.deepvenv311\Lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\.deepvenv311\Lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in .\.deepvenv311\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Downloading sentence_transformers-5.7.0-py3-none-any.whl (611 kB)
   ---------------------------------------- 0.0/611.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/611.3 kB ? eta -:--:--
   ----------------- ---------------------- 262.1/611.3 kB ? eta -:--:--
   ---------------------------------------- 611.3/611.3 kB 1.1 MB/s  0:00:00
Downloading transformers-5.15.0-py3-none-any.whl (11.7 MB)
   ---------------------------------------- 0.0/11.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.7 MB ? eta -:--:--
    --------------------------------------- 0.3/11.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.7 MB 1.1 MB/s eta 0:00:11
   -- ------------------------------------- 0.8/11.7 MB 1.1 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/11.7 MB 1.1 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.7 MB 1.1 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.7 MB 1.1 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.7 MB 1.1 MB/s eta 0:00:10
   ----- ---------------------------------- 1.6/11.7 MB 902.1 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/11.7 MB 902.1 kB/s eta 0:00:12
   ------ --------------------------------- 1.8/11.7 MB 798.8 kB/s eta 0:00:13
   ------ --------------------------------- 1.8/11.7 MB 798.8 kB/s eta 0:00:13
   ------- -------------------------------- 2.1/11.7 MB 815.6 kB/s eta 0:00:12
   -------- ------------------------------- 2.4/11.7 MB 854.9 kB/s eta 0:00:11
   -------- ------------------------------- 2.6/11.7 MB 872.8 kB/s eta 0:00:11
   --------- ------------------------------ 2.9/11.7 MB 882.9 kB/s eta 0:00:11
   --------- ------------------------------ 2.9/11.7 MB 882.9 kB/s eta 0:00:11
   ---------- ----------------------------- 3.1/11.7 MB 895.8 kB/s eta 0:00:10
   ----------- ---------------------------- 3.4/11.7 MB 906.8 kB/s eta 0:00:10
   ------------ --------------------------- 3.7/11.7 MB 904.9 kB/s eta 0:00:09
   ------------- -------------------------- 3.9/11.7 MB 917.5 kB/s eta 0:00:09
   ------------- -------------------------- 3.9/11.7 MB 917.5 kB/s eta 0:00:09
   -------------- ------------------------- 4.2/11.7 MB 918.5 kB/s eta 0:00:09
   --------------- ------------------------ 4.5/11.7 MB 932.1 kB/s eta 0:00:08
   ---------------- ----------------------- 4.7/11.7 MB 947.6 kB/s eta 0:00:08
   ---------------- ----------------------- 5.0/11.7 MB 952.7 kB/s eta 0:00:08
   ----------------- ---------------------- 5.2/11.7 MB 951.4 kB/s eta 0:00:07
   ------------------ --------------------- 5.5/11.7 MB 961.5 kB/s eta 0:00:07
   ------------------ --------------------- 5.5/11.7 MB 961.5 kB/s eta 0:00:07
   ------------------- -------------------- 5.8/11.7 MB 959.9 kB/s eta 0:00:07
   -------------------- ------------------- 6.0/11.7 MB 971.2 kB/s eta 0:00:06
   -------------------- ------------------- 6.0/11.7 MB 971.2 kB/s eta 0:00:06
   --------------------- ------------------ 6.3/11.7 MB 938.9 kB/s eta 0:00:06
   --------------------- ------------------ 6.3/11.7 MB 938.9 kB/s eta 0:00:06
   --------------------- ------------------ 6.3/11.7 MB 938.9 kB/s eta 0:00:06
   ---------------------- ----------------- 6.6/11.7 MB 888.9 kB/s eta 0:00:06
   ---------------------- ----------------- 6.6/11.7 MB 888.9 kB/s eta 0:00:06
   ----------------------- ---------------- 6.8/11.7 MB 892.4 kB/s eta 0:00:06
   ------------------------ --------------- 7.1/11.7 MB 892.0 kB/s eta 0:00:06
   ------------------------ --------------- 7.3/11.7 MB 898.8 kB/s eta 0:00:05
   ------------------------- -------------- 7.6/11.7 MB 910.3 kB/s eta 0:00:05
   -------------------------- ------------- 7.9/11.7 MB 918.0 kB/s eta 0:00:05
   --------------------------- ------------ 8.1/11.7 MB 923.5 kB/s eta 0:00:04
   --------------------------- ------------ 8.1/11.7 MB 923.5 kB/s eta 0:00:04
   ---------------------------- ----------- 8.4/11.7 MB 930.3 kB/s eta 0:00:04
   ----------------------------- ---------- 8.7/11.7 MB 937.0 kB/s eta 0:00:04
   ------------------------------ --------- 8.9/11.7 MB 941.5 kB/s eta 0:00:04
   ------------------------------- -------- 9.2/11.7 MB 942.9 kB/s eta 0:00:03
   -------------------------------- ------- 9.4/11.7 MB 944.0 kB/s eta 0:00:03
   -------------------------------- ------- 9.4/11.7 MB 944.0 kB/s eta 0:00:03
   --------------------------------- ------ 9.7/11.7 MB 948.2 kB/s eta 0:00:03
   --------------------------------- ------ 10.0/11.7 MB 950.6 kB/s eta 0:00:02
   ---------------------------------- ----- 10.2/11.7 MB 954.3 kB/s eta 0:00:02
   ----------------------------------- ---- 10.5/11.7 MB 956.5 kB/s eta 0:00:02
   ----------------------------------- ---- 10.5/11.7 MB 956.5 kB/s eta 0:00:02
   ------------------------------------ --- 10.7/11.7 MB 955.9 kB/s eta 0:00:02
   ------------------------------------- -- 11.0/11.7 MB 958.0 kB/s eta 0:00:01
   ------------------------------------- -- 11.0/11.7 MB 958.0 kB/s eta 0:00:01
   -------------------------------------- - 11.3/11.7 MB 939.5 kB/s eta 0:00:01
   -------------------------------------- - 11.3/11.7 MB 939.5 kB/s eta 0:00:01
   ---------------------------------------  11.5/11.7 MB 932.0 kB/s eta 0:00:01
   ---------------------------------------- 11.7/11.7 MB 932.9 kB/s  0:00:12
Downloading huggingface_hub-1.27.0-py3-none-any.whl (784 kB)
   ---------------------------------------- 0.0/784.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/784.9 kB ? eta -:--:--
   ------------- -------------------------- 262.1/784.9 kB ? eta -:--:--
   ------------------------- ------------ 524.3/784.9 kB 989.2 kB/s eta 0:00:01
   ---------------------------------------- 784.9/784.9 kB 1.0 MB/s  0:00:00
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 1.0 MB/s eta 0:00:04
   ------- -------------------------------- 0.8/4.0 MB 1.1 MB/s eta 0:00:03
   ---------- ----------------------------- 1.0/4.0 MB 1.1 MB/s eta 0:00:03
   ------------ --------------------------- 1.3/4.0 MB 1.1 MB/s eta 0:00:03
   --------------- ------------------------ 1.6/4.0 MB 1.1 MB/s eta 0:00:03
   --------------- ------------------------ 1.6/4.0 MB 1.1 MB/s eta 0:00:03
   ------------------ --------------------- 1.8/4.0 MB 1.1 MB/s eta 0:00:03
   -------------------- ------------------- 2.1/4.0 MB 1.1 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 1.1 MB/s eta 0:00:02
   ------------------------- -------------- 2.6/4.0 MB 1.1 MB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 1.1 MB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 1.1 MB/s eta 0:00:02
   ------------------------------- -------- 3.1/4.0 MB 1.1 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 1.1 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 987.0 kB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 987.0 kB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 987.0 kB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 883.1 kB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 883.1 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 900.6 kB/s  0:00:04
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 1.2 MB/s eta 0:00:02
   ----------- ---------------------------- 0.8/2.7 MB 1.1 MB/s eta 0:00:02
   --------------- ------------------------ 1.0/2.7 MB 1.0 MB/s eta 0:00:02
   --------------- ------------------------ 1.0/2.7 MB 1.0 MB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.7 MB 1.0 MB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.7 MB 1.0 MB/s eta 0:00:02
   -------------------------- ------------- 1.8/2.7 MB 1.0 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.0 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.7 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 1.1 MB/s  0:00:02
Downloading regex-2026.7.19-cp311-cp311-win_amd64.whl (277 kB)
Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Downloading tqdm-4.70.0-py3-none-any.whl (80 kB)
Downloading typer-0.27.1-py3-none-any.whl (122 kB)
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: tqdm, shellingham, safetensors, regex, hf-xet, click, annotated-doc, typer, huggingface-hub, tokenizers, transformers, sentence-transformers

   ----------------------------------------  0/12 [tqdm]
   ----------------------------------------  0/12 [tqdm]
   ----------------------------------------  0/12 [tqdm]
   --- ------------------------------------  1/12 [shellingham]
   ------ ---------------------------------  2/12 [safetensors]
   ---------- -----------------------------  3/12 [regex]
   ---------------- -----------------------  5/12 [click]
   ---------------- -----------------------  5/12 [click]
   ---------------- -----------------------  5/12 [click]
   ----------------------- ----------------  7/12 [typer]
   ----------------------- ----------------  7/12 [typer]
   ----------------------- ----------------  7/12 [typer]
   ----------------------- ----------------  7/12 [typer]
   ----------------------- ----------------  7/12 [typer]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   -------------------------- -------------  8/12 [huggingface-hub]
   ------------------------------ ---------  9/12 [tokenizers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]
   --------------------------------- ------ 10/12 [transformers]

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
from sentence_transformers import SentenceTransformer

print("Loading Transformer model...")

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

print("Transformer loaded successfully!")

Loading Transformer model...

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\Rythem\OneDrive\Desktop\deep learning\.deepvenv311\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Rythem\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Transformer loaded successfully!

In [15]:
# Get medicine names
medicine_names = df["medicine_text"].tolist()

print("Total medicines:", len(medicine_names))

# Generate embeddings
embeddings = model.encode(
    medicine_names,
    show_progress_bar=True,
    batch_size=32
)

print("Embedding shape:", embeddings.shape)

Total medicines: 11498

Batches:   0%|          | 0/360 [00:00<?, ?it/s]

Embedding shape: (11498, 384)

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

def search_medicine(query, top_k=5):

    # Convert user query into embedding
    query_embedding = model.encode([query])

    # Compare query with combined medicine information
    similarities = cosine_similarity(
        query_embedding,
        combined_embeddings
    )[0]

    # Get top matches
    top_indices = similarities.argsort()[-top_k:][::-1]

    results = df.iloc[top_indices].copy()

    results["Similarity"] = similarities[top_indices]

    return results

In [17]:
results = search_medicine("Augmentin 625", top_k=5)

display(
    results[
        [
            "Medicine Name",
            "Composition",
            "Uses",
            "Side_effects",
            "Similarity"
        ]
    ]
)

,Medicine Name,Composition,Uses,Side_effects,Similarity
1,Augmentin 625 Duo Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,Vomiting Nausea Diarrhea Mucocutaneous candidi...,0.730238
102,Augmentin 375 Tablet,Amoxycillin (250mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,Vomiting Nausea Diarrhea Mucocutaneous candidi...,0.672182
79,Augmentin 1.2gm Injection,Amoxycillin (1000mg) + Clavulanic Acid (200mg),Treatment of Bacterial infections,Vomiting Nausea Diarrhea Mucocutaneous candidi...,0.662974
205,Augpen LB 625 Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg) ...,Bacterial infections,Nausea Diarrhea Vomiting Flatulence Rash Aller...,0.595600
242,Augpen 625 BID Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,Vomiting Nausea Diarrhea Mucocutaneous candidi...,0.595085

In [18]:
def get_medicine_info(query):

    results = search_medicine(query, top_k=1)

    medicine = results.iloc[0]

    print("\n" + "=" * 60)
    print("MEDICINE INFORMATION")
    print("=" * 60)

    print("Medicine Name :", medicine["Medicine Name"])
    print("Composition   :", medicine["Composition"])
    print("Uses          :", medicine["Uses"])
    print("Side Effects  :", medicine["Side_effects"])
    print("Manufacturer  :", medicine["Manufacturer"])

    print("\nReview:")
    print("Excellent :", medicine["Excellent Review %"], "%")
    print("Average   :", medicine["Average Review %"], "%")
    print("Poor      :", medicine["Poor Review %"], "%")

    print("\nSimilarity Score :", round(medicine["Similarity"], 4))

In [20]:
get_medicine_info("Dolo")

============================================================
MEDICINE INFORMATION
============================================================
Medicine Name : Dolo Drops
Composition   : Paracetamol (100mg/ml)
Uses          :  Pain reliefTreatment of Fever
Side Effects  : Indigestion Stomach pain Nausea Vomiting
Manufacturer  : Micro Labs Ltd

Review:
Excellent : 36 %
Average   : 39 %
Poor      : 25 %

Similarity Score : 0.76

In [21]:
results = search_medicine("Dolo", top_k=5)

display(
    results[
        [
            "Medicine Name",
            "Composition",
            "Uses",
            "Side_effects",
            "Similarity"
        ]
    ]
)

,Medicine Name,Composition,Uses,Side_effects,Similarity
1412,Dolo Drops,Paracetamol (100mg/ml),Pain reliefTreatment of Fever,Indigestion Stomach pain Nausea Vomiting,0.760010
1457,Dolocaine Cream,Prilocaine (25mg/gm) + Lidocaine (25mg/gm),Local anesthesia (Numb tissues in a specific ...,Application site reactions burning irritation ...,0.500256
1615,Dolo 156.25mg Suspension,Paracetamol (156.25mg/5ml),Pain reliefTreatment of Fever,Stomach pain Nausea Vomiting,0.480436
6417,Nvm Dolo Tablet SR,Methylcobalamin (1500mcg) + Pregabalin (75mg),Treatment of Neuropathic pain,Dizziness Sleepiness Tiredness Uncoordinated b...,0.456316
1580,Doberol Capsule,Calcium Dobesilate (500mg),Treatment of PilesTreatment of Varicose veins,Skin rash Fever Nausea Vomiting,0.444473

In [25]:
get_medicine_info("Paracetam")

============================================================
MEDICINE INFORMATION
============================================================
Medicine Name : Paramet Tablet
Composition   : Metoclopramide (5mg) + Paracetamol (500mg)
Uses          :  Migraine
Side Effects  : Restlessness Tiredness Drowsiness
Manufacturer  : Wallace Pharmaceuticals Pvt Ltd

Review:
Excellent : 42 %
Average   : 44 %
Poor      : 14 %

Similarity Score : 0.6017

In [26]:
print(df["Image URL"].iloc[0])

https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/f5a26c491e4d48199ab116a69a969be3.jpg

In [27]:
from IPython.display import Image, display

display(Image(url=df["Image URL"].iloc[0]))

In [28]:
from IPython.display import Image, display

def get_medicine_info(query):

    results = search_medicine(query, top_k=1)

    medicine = results.iloc[0]

    print("\n" + "=" * 60)
    print("MEDICINE INFORMATION")
    print("=" * 60)

    print("Medicine Name :", medicine["Medicine Name"])
    print("Composition   :", medicine["Composition"])
    print("Uses          :", medicine["Uses"])
    print("Side Effects  :", medicine["Side_effects"])
    print("Manufacturer  :", medicine["Manufacturer"])

    print("\nReview:")
    print("Excellent :", medicine["Excellent Review %"], "%")
    print("Average   :", medicine["Average Review %"], "%")
    print("Poor      :", medicine["Poor Review %"], "%")

    print("\nSimilarity Score :", round(medicine["Similarity"], 4))

    # Display medicine image
    print("\nMedicine Image:")
    display(Image(url=medicine["Image URL"]))

In [31]:
get_medicine_info("Paracetamol 650")

============================================================
MEDICINE INFORMATION
============================================================
Medicine Name : Paragreat 650mg Tablet
Composition   : Paracetamol (650mg)
Uses          :  Pain reliefTreatment of Fever
Side Effects  : Stomach pain Nausea Vomiting
Manufacturer  : Mankind Pharma Ltd

Review:
Excellent : 39 %
Average   : 33 %
Poor      : 28 %

Similarity Score : 0.711

Medicine Image:

In [32]:
df["combined_text"] = (
    "Medicine: " + df["Medicine Name"].astype(str) +
    " | Composition: " + df["Composition"].astype(str) +
    " | Uses: " + df["Uses"].astype(str)
)

display(df[["Medicine Name", "combined_text"]].head())

              Medicine Name                                      combined_text
0   Avastin 400mg Injection  Medicine: Avastin 400mg Injection | Compositio...
1  Augmentin 625 Duo Tablet  Medicine: Augmentin 625 Duo Tablet | Compositi...
2       Azithral 500 Tablet  Medicine: Azithral 500 Tablet | Composition: A...
3          Ascoril LS Syrup  Medicine: Ascoril LS Syrup | Composition: Ambr...
4         Aciloc 150 Tablet  Medicine: Aciloc 150 Tablet | Composition: Ran...

In [33]:
combined_texts = df["combined_text"].tolist()

combined_embeddings = model.encode(
    combined_texts,
    show_progress_bar=True,
    batch_size=32
)

print("Embedding shape:", combined_embeddings.shape)

Batches:   0%|          | 0/360 [00:00<?, ?it/s]

Embedding shape: (11498, 384)

In [34]:
print(df["combined_text"].iloc[1])

Medicine: Augmentin 625 Duo Tablet | Composition: Amoxycillin  (500mg) +  Clavulanic Acid (125mg) | Uses: Treatment of Bacterial infections

In [36]:
results = search_medicine("Augmentin 625", top_k=5)

display(
    results[
        [
            "Medicine Name",
            "Composition",
            "Uses",
            "Similarity"
        ]
    ]
)

,Medicine Name,Composition,Uses,Similarity
1,Augmentin 625 Duo Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,0.595899
102,Augmentin 375 Tablet,Amoxycillin (250mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,0.528600
63,Augmentin 1000 Duo Tablet,Amoxycillin (875mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,0.524248
79,Augmentin 1.2gm Injection,Amoxycillin (1000mg) + Clavulanic Acid (200mg),Treatment of Bacterial infections,0.497699
242,Augpen 625 BID Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,0.491728

In [37]:
results = search_medicine(
    "medicine for bacterial infection containing amoxicillin",
    top_k=5
)

display(
    results[
        [
            "Medicine Name",
            "Composition",
            "Uses",
            "Similarity"
        ]
    ]
)

,Medicine Name,Composition,Uses,Similarity
4970,Mox 500mg Capsule,Amoxycillin (500mg),Treatment of Bacterial infections,0.756813
46,Almox 500 Capsule,Amoxycillin (500mg),Treatment of Bacterial infections,0.752393
183,Almox 250 Capsule,Amoxycillin (250mg),Treatment of Bacterial infections,0.751128
5443,Moxikem 500mg Capsule,Amoxycillin (500mg),Treatment of Bacterial infections,0.750299
5096,Mox 250mg Capsule,Amoxycillin (250mg),Treatment of Bacterial infections,0.750212

In [38]:
results = search_medicine(
    "medicine used for cough with mucus",
    top_k=5
)

display(
    results[
        [
            "Medicine Name",
            "Composition",
            "Uses",
            "Similarity"
        ]
    ]
)

,Medicine Name,Composition,Uses,Similarity
612,Aerodil-LS Expectorant,Ambroxol (15mg/5ml) + Levosalbutamol (0.5mg/5m...,Treatment of Cough with mucus,0.756559
10640,Ventryl Expectorant,Ambroxol (30mg/5ml) + Guaifenesin (100mg/5ml) ...,Cough with mucus,0.755545
335,Aerodil Expectorant,Ambroxol (15mg/5ml) + Guaifenesin (50mg/5ml) +...,Treatment of Cough with mucus,0.753869
5630,Mucaryl LS Syrup,Ambroxol (30mg/5ml) + Levosalbutamol (1mg/5ml)...,Treatment of Cough with mucus,0.749620
5094,Macbery LS Expectorant,Ambroxol (30mg/5ml) + Levosalbutamol (1mg/5ml)...,Treatment of Cough with mucus,0.742499

In [44]:
results = search_medicine("Augmentin 625", top_k=5)

display(
    results[
        [
            "Medicine Name",
            "Composition",
            "Uses",
            "Similarity"
        ]
    ]
)

,Medicine Name,Composition,Uses,Similarity
1,Augmentin 625 Duo Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,0.595899
102,Augmentin 375 Tablet,Amoxycillin (250mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,0.528600
63,Augmentin 1000 Duo Tablet,Amoxycillin (875mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,0.524248
79,Augmentin 1.2gm Injection,Amoxycillin (1000mg) + Clavulanic Acid (200mg),Treatment of Bacterial infections,0.497699
242,Augpen 625 BID Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),Treatment of Bacterial infections,0.491728

In [45]:
from IPython.display import Image, display

best_medicine = results.iloc[0]

print("Medicine:", best_medicine["Medicine Name"])
print("Similarity:", round(best_medicine["Similarity"], 4))

display(Image(url=best_medicine["Image URL"]))

Medicine: Augmentin 625 Duo Tablet
Similarity: 0.5959

In [46]:
from IPython.display import Image, display

def show_best_medicine(query):

    results = search_medicine(query, top_k=5)

    # Best matching medicine
    best = results.iloc[0]

    print("=" * 60)
    print("💊 BEST MATCH")
    print("=" * 60)

    print("Medicine Name :", best["Medicine Name"])
    print("Composition   :", best["Composition"])
    print("Uses          :", best["Uses"])
    print("Side Effects  :", best["Side_effects"])
    print("Manufacturer  :", best["Manufacturer"])

    print("\nReviews")
    print("Excellent :", best["Excellent Review %"], "%")
    print("Average   :", best["Average Review %"], "%")
    print("Poor      :", best["Poor Review %"], "%")

    print("\nSimilarity :", round(best["Similarity"], 4))

    print("\nMedicine Image:")
    display(Image(url=best["Image URL"]))

    print("\n" + "=" * 60)
    print("🔎 SIMILAR MEDICINES")
    print("=" * 60)

    display(
        results.iloc[1:][
            [
                "Medicine Name",
                "Composition",
                "Similarity"
            ]
        ]
    )

In [47]:
show_best_medicine("Augmentin 625")

============================================================
💊 BEST MATCH
============================================================
Medicine Name : Augmentin 625 Duo Tablet
Composition   : Amoxycillin  (500mg) +  Clavulanic Acid (125mg)
Uses          : Treatment of Bacterial infections
Side Effects  : Vomiting Nausea Diarrhea Mucocutaneous candidiasis
Manufacturer  : Glaxo SmithKline Pharmaceuticals Ltd

Reviews
Excellent : 47 %
Average   : 35 %
Poor      : 18 %

Similarity : 0.5959

Medicine Image:

============================================================
🔎 SIMILAR MEDICINES
============================================================

,Medicine Name,Composition,Similarity
102,Augmentin 375 Tablet,Amoxycillin (250mg) + Clavulanic Acid (125mg),0.528600
63,Augmentin 1000 Duo Tablet,Amoxycillin (875mg) + Clavulanic Acid (125mg),0.524248
79,Augmentin 1.2gm Injection,Amoxycillin (1000mg) + Clavulanic Acid (200mg),0.497699
242,Augpen 625 BID Tablet,Amoxycillin (500mg) + Clavulanic Acid (125mg),0.491728

In [50]:
import numpy as np

np.save(
    "models/medicine_embeddings.npy",
    combined_embeddings
)

print("Embeddings saved successfully!")

FileNotFoundError: [Errno 2] No such file or directory: 'models/medicine_embeddings.npy'

In [51]:
import os

os.makedirs("models", exist_ok=True)
os.makedirs("data", exist_ok=True)

print("Folders created successfully!")

Folders created successfully!

In [52]:
import numpy as np

np.save(
    "models/medicine_embeddings.npy",
    combined_embeddings
)

print("Embeddings saved successfully!")

Embeddings saved successfully!

In [53]:
df.to_csv(
    "data/medicines_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [54]:
import os

print("Embeddings:", os.path.exists("models/medicine_embeddings.npy"))
print("Dataset:", os.path.exists("data/medicines_cleaned.csv"))

Embeddings: True
Dataset: True

In [55]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles and folders:")
for item in os.listdir():
    print(item)

Current folder:
c:\Users\Rythem\OneDrive\Desktop\deep learning

Files and folders:
# Overfitting.md
.deepvenv311
cnn.ipynb
data
deep.ipynb
heart.ipynb
Medicine-Assistant.ipynb
MediGuide.ipynb
models

In [56]:
print(
    "Embeddings:",
    os.path.abspath("models/medicine_embeddings.npy")
)

print(
    "Dataset:",
    os.path.abspath("data/medicines_cleaned.csv")
)

Embeddings: c:\Users\Rythem\OneDrive\Desktop\deep learning\models\medicine_embeddings.npy
Dataset: c:\Users\Rythem\OneDrive\Desktop\deep learning\data\medicines_cleaned.csv